spring:
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET_ID}
            client-name: Yandex
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/yandex
            client-authentication-method: post
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id
